"""Parity: the wasm engine must reproduce the native engine byte-for-byte.

The fixture is generated by ``generate_fixture.py`` from the sibling Rust engine.
These assertions are exact equality, not tolerance — the SPK-over-wasm spike
established that the wasm and native builds agree to the bit, so anything less
than equality here is a real regression, not floating-point noise.
"""
from __future__ import annotations

import json
import pathlib

import pytest

from vedaksha._engine import Engine

FIXTURE = pathlib.Path(__file__).parent / "native_fixture.json"


@pytest.fixture(scope="module")
def cases() -> dict:
    if not FIXTURE.exists():
        pytest.fail(
            f"{FIXTURE} missing; regenerate with "
            "python tests/conformance/generate_fixture.py"
        )
    return json.loads(FIXTURE.read_text())


@pytest.fixture(scope="module")
def engine() -> Engine:
    return Engine()


def test_fixture_has_cases(cases: dict) -> None:
    # A skipped or empty conformance run must fail loudly, never pass quietly.
    assert len(cases) >= 4, "parity fixture unexpectedly small"


def test_wasm_matches_native(cases: dict, engine: Engine) -> None:
    mismatches = []
    for label, case in cases.items():
        wasm_resp = engine.call_json(case["request"])
        native_resp = json.loads(case["response"])
        if wasm_resp != native_resp:
            mismatches.append(label)
    assert not mismatches, f"wasm != native for: {mismatches}"


def test_natal_chart_values_bit_identical(cases: dict, engine: Engine) -> None:
    """Drill into the natal chart: every leaf value identical, not just equal JSON."""
    case = cases["natal_j2000"]
    wasm = engine.call_json(case["request"])
    native = json.loads(case["response"])

    def leaves(obj, path=""):
        if isinstance(obj, dict):
            for k, v in obj.items():
                yield from leaves(v, f"{path}.{k}")
        elif isinstance(obj, list):
            for i, v in enumerate(obj):
                yield from leaves(v, f"{path}[{i}]")
        else:
            yield path, obj

    w = dict(leaves(wasm))
    n = dict(leaves(native))
    assert w.keys() == n.keys()
    diffs = {k: (n[k], w[k]) for k in n if n[k] != w[k]}
    assert not diffs, f"leaf mismatches: {diffs}"
