"""Vedākṣa — Astronomical ephemeris and astrological computation."""

def compute_dasha(moon_longitude: float, birth_jd: float, levels: int = 3) -> str: ...
def get_nakshatra(sidereal_longitude: float) -> dict: ...
def compute_varga(longitude: float, varga: str) -> int: ...
def compute_houses(ramc: float, latitude: float, obliquity: float, system: str = "Placidus") -> dict: ...
def tropical_to_sidereal(tropical_longitude: float, ayanamsha: str = "Lahiri", jd: float = 2451545.0) -> float: ...
def get_ayanamsha(ayanamsha: str = "Lahiri", jd: float = 2451545.0) -> float: ...
def calendar_to_jd(year: int, month: int, day: float) -> float: ...
def planet_name(index: int, language: str = "en") -> str: ...
def sign_name(index: int, language: str = "en") -> str: ...
def nakshatra_name_i18n(index: int, language: str = "en") -> str: ...
