// Copyright © 2026 ArthIQ Labs LLC. All rights reserved.
// Vedākṣa — Axis of Wisdom
// Licensed under BSL 1.1. See LICENSE file.

//! Static coefficient tables for analytical ephemeris series.
//!
//! Each planet module contains `X0`..`X5`, `Y0`..`Y5`, `Z0`..`Z5` arrays of
//! `(amplitude, phase, frequency)` triples for VSOP87A evaluation:
//!
//! ```text
//! coord_alpha(t) = t^alpha * sum_i [A_i * cos(B_i + C_i * t)]
//! ```
//!
//! where `t` is Julian millennia from J2000.0 (JDE 2451545.0).

// VSOP87A planet coefficients (generated by scripts/generate_vsop87a.py)
pub mod mercury;
pub mod venus;
pub mod earth;
pub mod mars;
pub mod jupiter;
pub mod saturn;
pub mod uranus;
pub mod neptune;

// ELP/MPP02 lunar coefficients (generated by scripts/generate_elpmpp02.py)
pub mod moon_longitude;
pub mod moon_latitude;
pub mod moon_distance;
